### ISSUE TITLE
Debounce#cancel undefined

### ISSUE THREAD

**Issue by mmw** [steelsojka/lodash-decorators#10] opened 2015-07-29 23:28 UTC
For some reason it looks like we lost the `cancel` function from `debounce`.

Example:

```
class Search extends React.Component {
  static propTypes = {
    setSearchQuery: React.PropTypes.func
  };

  state = { searchQuery: null };

  @debounce(200)
  debouncedSearch(searchQuery) {
    this.props.setSearchQuery(searchQuery);
  }

  handleSearch = (evt) => {
    const searchQuery = evt.target.value.trim();

    if(searchQuery === '') {
      this.clearSearchQuery();
    } else {
      this.debouncedSearch(searchQuery);
      this.setState({ searchQuery });
    }
  }

  clearSearchQuery = () => {
    const searchQuery = null;

    this.debouncedSearch.cancel(); // undefined
    this.props.setSearchQuery(searchQuery);
    this.setState({ searchQuery });
  }

  render() {
    return (
      <input
        type="text"
        onChange={this.handleSearch}
        value={this.state.searchQuery}
      />
    );
  }
}
```

Is anyone able to reproduce this or is it just me?

**Comment by steelsojka** [comment] 2015-07-30 03:41
This is a legit bug. It's because the decorators that apply to instances and not to the prototype directly use a proxy method that performs a look up through a WeakMap for the instance(debounced) method for that instance. The `cancel` method for the debounced function is never applied to the proxy function. I'll look into this tomorrow and try and find a solution.

**Comment by steelsojka** [comment] 2015-07-31 12:58
This is resolved in v1.0.0

**Closed as completed by steelsojka** 2015-07-31 12:58 UTC

**Comment by mmw** [comment] 2015-07-31 16:46
Thanks for the quick fix!

**Comment by steelsojka** [comment] 2015-07-31 18:40
No problem. There are some API changes that come with the 1.0.0 release. So double check that it doesn't affect any of your code.

**Comment by mmw** [comment] 2015-08-18 18:53
Sorry, I was only able to get around to updating lodash-decorators today. After updating I'm getting `Uncaught TypeError: Cannot assign to read only property 'debouncedFunction' of #<Component>` type error. 

Would this be related to the API changes made in V1.0.0? I'm using `@debounce` with `@bindAll` on my component's class

**Comment by steelsojka** [comment] 2015-08-21 01:24
Can you give me a code snippet that easily reproduces it? Something like this?

``` javascript
@BindAll()
class Person {
    @Debounce(100)
    debouncedFn() {}
}
```

**Comment by mmw** [comment] 2015-08-21 15:13
Yep, the snippet you pasted is exactly right. I'm using it with webpack and react so I'm exporting the class and extending `React.Component` as well.

Also seems related: the debounced function is no longer on the prototype. Previously I was successfully stubbing the function in my tests, which also no longer works with the V1 update.

```
describe('Person test', () => {
  let dbStub;

  beforeEach(() => {
    dbStub = sinon.stub(Person.prototype, 'debouncedFn');
  });

  // test cases...
});
```

Results in: `TypeError: Attempted to wrap undefined property debouncedFn as function`

**Comment by steelsojka** [comment] 2015-08-24 13:14
I couldn't get the error you describe to throw with that example.  Could it have something to do with the React.Component class?

As for the prototype stubbing that is expected with the way you are stubbing the method. Since `debounce` is a decorator that is applied at the instance and not the prototype, the prototype method is using a getter and setter. So when you are accessing through the prototype the getter is getting invoked and looking up the debounced function that belongs to the current context with a `WeakMap`. So you'll have to stub the debounced function AFTER the `Person` class is instantiated.

Since there is no standard way to do instance level decorators in the current spec, the getter and setter method is a workaround/hack so it still has some wrinkles to be worked out.

I will test a little bit more and see if I can't find a solution for the issue.

**Comment by mmw** [comment] 2015-08-24 16:36
It seems like it's something else causing the error. If I remove `extends React.Component` and the features it provides me with I'm still experiencing this error. I'll try to create an example of this occurring separate from my project

WRT to stubbing does that mean that pre V1 it was incorrectly assigned to the prototype? Since I'm using React I'm not entirely sure where/how I'd need to stub the debounced function

**Comment by steelsojka** [comment] 2015-08-24 18:08
Before the refactor, You weren't actually stubbing the debounced function, just a proxy that accessed the debounced function for that instance from a WeakMap. This is why the `cancel` method on the debounce didn't exist because you never had the actual debounced function.

**Comment by mmw** [comment] 2015-08-25 15:53
Ok, thanks for clarifying. I wasn't able to reproduce the issue in a skeleton implementation of webpack and react so it looks like there is something about the way my project is configured that's causing the issues. I'll have to investigate on my own I suppose, thanks for your help! If I manage to come up with any steps to reproduce I'll let you know as it may be relevant to the project.

**Comment by steelsojka** [comment] 2015-08-31 17:25
Cool. There most likely will be some weird one off scenarios that aren't accounted for. Please let me know if you discover them, so they can get fixed. Thanks!
